name = "Jacobi"
uuid = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"
authors = ["Paulo José Saiz Jabardo <pjabardo@gmail.com> and contributors"]
version = "0.5.0"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Polynomials = "1.1"
SpecialFunctions = "0.8, 0.9, 0.10, 1.0"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
